services:
    php8.1-node20.8:
        container_name: "php8.1-node20.8"
        build:
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "8000:8000"
        working_dir: /var/www/html
