version: '3.7'
services:
    appdev:
        container_name: "comitidev-php"
        build:
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "8000:8000"
            - "8088:8080"
            - "8889:8889"
            - "8887:8887"
            - "9090:9090"
        working_dir: /var/www/html

    mysql:
        container_name: "comitidev-mysql"
        image: mysql:5.5.49
        ports:
            - "33006:3306"
        command: --max_allowed_packet=1073741824      # Set max_allowed_packet to 256M (or any other value)
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=comiti_rec
            - MYSQL_USER=comiti_rec
            - MYSQL_PASSWORD=comiti_rec
        working_dir: /root

    phpmyadmin:
        container_name: "comitidev-phpmyadmin"
        image: phpmyadmin/phpmyadmin:5.0.4
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_PORT: 3306
        ports:
            - "8080:80"
